version: '3.7'

services:
  mongodb:
    image: mongo:latest
    container_name: nest-auth
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - nest-auth:/data/db

volumes:
  nest-auth: